---
- hosts: vm
  become: yes
  tasks:
    - name: Create multiple users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        groups: "{{ item.groups | default(omit) }}"
        shell: "{{ item.shell }}"
        state: present  # use absent for deleting users with specific UIDs
      loop:
        - { name: 'alice', uid: 1005, groups: 'root', shell: '/bin/bash' }
        - { name: 'bob', uid: 1006, groups: 'root', shell: '/bin/bash' }
        - { name: 'charlie', uid: 1007, groups: 'root', shell: '/bin/bash' }