##### the play book consist of conditional statements ##### command used is when module
---
- hosts: vm
  become: yes
  tasks:
    - name: install httpd package
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: install nginx package
      yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "Debian"    

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"  